---
language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install tox

script:
  - tox

addons:
  apt:
    packages:
    - python-dev
    - python-pip
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
